version: '3.8'
services:
  # PHP Service
    php:
        container_name: php
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
            - CONTAINER_ROLE=app
        working_dir: /var/www/html/
        volumes:
            - ./:/var/www/html/
        ports:
            - 8000:8000
        depends_on:
            - database

  # Database Server
    database:
        image: mysql:8.0.28
        restart: always   
        ports:
            - 33306:3306
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=secret
        volumes:
            - db-data:/var/lib/mysql
  # Create phpmyadmin service to view the database in the GUI
    phpmyadmin:
        image: phpmyadmin:5.2.1
        links:
            - database
        ports:
            - 4000:80      
        environment:
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}

volumes:
    db-data: ~